version: "3.8"

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9090:9090"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - "./minio/data:/data"
