version: '3.8'

services:  
  conduktor-postgresql:
    image: postgres:14
    hostname: conduktor-postgresql
    volumes:
      - conduktor-pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "conduktor_password"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    image: conduktor/conduktor-console:1.28.0
    depends_on:
      - conduktor-postgresql
    ports:
      - "8091:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_ORGANIZATION_NAME: "getting-started"
      CDK_DATABASE_URL: "postgresql://conduktor:conduktor_password@conduktor-postgresql:5432/conduktor-console"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-platform:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080
      
  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.28.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"

volumes:
  conduktor-pg_data: {}
  conduktor_data: {}
