version: '3.5'

services:
  kafka-0:
    container_name: kafka-0
    hostname: kafka-0
    image: bitnami/kafka:3.8.1
    ports:
      - "29092:29092"
      - "29095:9404"
    restart: always
    networks:
      - kafka_network
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      # KAFKA CLUSTER
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093
      # - KAFKA_CFG_SUPER_USERS=User:sa
      # LISTENERS
      - KAFKA_CFG_LISTENERS=EXTERNAL://:29092,PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://192.168.0.110:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      # BROKER SETTINGS
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # - KAFKA_INTER_BROKER_USER=sa
      # - KAFKA_INTER_BROKER_PASSWORD=000000
      # - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      # CONTROLLER SETTINGS
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      # - KAFKA_CONTROLLER_USER=sa
      # - KAFKA_CONTROLLER_PASSWORD=000000
      # CLIENT SETTINGS
      # - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL
      # - KAFKA_CLIENT_USERS=sa,da,va
      # - KAFKA_CLIENT_PASSWORDS=000000,111111,222222
      # ACL
      # - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      # - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=false
      # SSL
      # - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      # - KAFKA_CERTIFICATE_PASSWORD=supersecret
      # - KAFKA_TLS_TYPE=JKS
      # SASL
      # - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      # COMMON SETTINGS
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # - EXTRA_ARGS=-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.19.0.jar=9404:/opt/jmx-exporter/kafka-3_0_0.yml

volumes:
  kafka_data:

networks:
  kafka_network:
