version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    shm_size: '1g'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - /path_to_local_volume:/var/lib/postgresql/data
